default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: app_development
  username: root
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD", "secret") %>

test:
  <<: *default
  database: app_test
  username: app
  password: app_pass
  host: db

production:
  <<: *default
  database: production
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  url: <%= ENV["DATABASE_URL"] %>
