services:
  db:
    image: mysql:8.0
    container_name: mwk-dev-db
    command: --skip-log-bin
    restart: unless-stopped
    platform: linux/arm64
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: app_development
      MYSQL_USER: app
      MYSQL_PASSWORD: app_pass
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$${MYSQL_ROOT_PASSWORD} -h 127.0.0.1 --silent"]
      interval: 5s
      retries: 20
    volumes:
      - dev-db-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
    # ポート公開が不要なら ports: は付けない
    # ports:
    #   - "3308:3306"

  backend:
    build:
      context: ./backend
      args:
        WORKDIR: ${WORKDIR}
        API_CONTAINER_PORT: ${API_CONTAINER_PORT}
    container_name: mwk-dev-backend
    depends_on:
      db:
        # ← ヘルスチェック完了を待つ
        condition: service_healthy
    command: >
      /bin/sh -c "
        rm -f tmp/pids/server.pid &&
        bundle check || bundle install &&
        bundle exec rails db:prepare &&
        # DB が空ならシードを流す
        bundle exec rails runner 'Rails.application.load_seed if Post.count.zero?' &&
        bundle exec rails s -p ${API_CONTAINER_PORT} -b 0.0.0.0
      "
    env_file:
      - ./backend/.env
    environment:
      RAILS_ENV: development
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      API_DOMAIN: localhost:${FRONT_PORT}
    ports:
      - '${API_PORT}:${API_CONTAINER_PORT}'
    volumes:
      - dev-bundle-cache:/usr/local/bundle
      - ./backend:${WORKDIR}:cached

  frontend:
    build:
      context: ./frontend
      args:
        WORKDIR: ${WORKDIR}
        CONTAINER_PORT: ${FRONT_CONTAINER_PORT}
        API_URL: http://localhost:${API_PORT}
    container_name: mwk-dev-frontend
    command: yarn dev
    depends_on:
      - backend
    ports:
      - "${FRONT_PORT}:${FRONT_CONTAINER_PORT}"
    volumes:
      - ./frontend:/${WORKDIR}:cached
      - dev-node-modules:/${WORKDIR}/node_modules

volumes:
  dev-bundle-cache:
  dev-db-data:
  dev-node-modules:
