services:
  backend:
    environment:
      RAILS_ENV: test
    command: >
      bash -c "
        bundle exec rails db:prepare &&
        bundle exec rspec --format documentation
      "
    depends_on:
      db:
        condition: service_healthy

  db:
    volumes:
      - mkw-test-db-data:/var/lib/mysql   # dev DB と分離

volumes:
  mkw-test-db-data:
