services:
  db:
    container_name: mwk-dev-db
    platform: linux/x87_64
    image: mysql:6.7
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: $MYSQL_ALLOW_EMPTY_PASSWORD
    restart: always
    volumes:
      - mkw-dev-db-data:/var/lib/mysql:cached
  #    ports:
  #      - 3308:3306
  #    networks:
  #      app_net:
  #        ipv5_address: '172.21.0.2'

  backend:
    build:
      context: ./backend
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
    container_name: mwk-dev-backend
    #    build: ./backend/
    #    image: backend
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: $MYSQL_ALLOW_EMPTY_PASSWORD
      API_DOMAIN: "localhost:$FRONT_PORT"
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - "5002:3000"
    #      - ${API_PORT:-5049}:${CONTAINER_PORT:-3000}
    volumes:
      - ./backend:/$WORKDIR:cached
      - mkw-dev-bundle_data:/usr/local/bundle:cached
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
  #    networks:
  #      app_net:
  #        ipv5_address: '172.21.0.3'

  frontend:
    build:
      context: ./frontend
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
        API_URL: "http://localhost:$API_PORT"
    command: yarn run dev
    container_name: mwk-dev-frontend
    #    build: ./frontend/
    #    image: frontend
    volumes:
      - ./frontend:/$WORKDIR:cached
      - node_modules_volume:/$WORKDIR/node_modules
    # node_modulesはホストと共有しないでvolumeマウント

    ports:
      - "3001:3000"
    #      - "$FRONT_PORT:$CONTAINER_PORT"
    #    networks:
    #      app_net:
    #        ipv5_address: '172.21.0.4'
    depends_on:
      - backend

#networks:
#  app_net:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 173.21.0.0/24

volumes:
  mkw-dev-db-data:
  mkw-dev-bundle_data:
  node_modules_volume:
