services:
  db:
    image: mysql:8.0
    container_name: mwk-dev-db
    command: --skip-log-bin
    restart: unless-stopped
    platform: linux/x86_64
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: app_development
      MYSQL_USER: app
      MYSQL_PASSWORD: app_pass
    healthcheck:                   # ── ★追加: 起動完了を検知
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$${MYSQL_ROOT_PASSWORD} -h 127.0.0.1 --silent"]
      interval: 5s
      retries: 20
    volumes:
      - mkw-dev-db-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
    # ポート公開が不要なら ports: は付けない
    # ports:
    #   - "3308:3306"

  backend:
    build:
      context: ./backend
      args:
        WORKDIR: ${WORKDIR}
        CONTAINER_PORT: ${API_CONTAINER_PORT}
    container_name: mwk-dev-backend
    command: >
      /bin/sh -c "
        rm -f tmp/pids/server.pid &&
        bundle exec rails s -p ${API_CONTAINER_PORT} -b 0.0.0.0
      "
    environment:
      RAILS_ENV: development
      API_DOMAIN: localhost:${FRONT_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    ports:
      - "${API_PORT}:${API_CONTAINER_PORT}"
    volumes:
      - ./backend:/${WORKDIR}:cached
      - mkw-dev-bundle_data:/usr/local/bundle:cached

  frontend:
    build:
      context: ./frontend
      args:
        WORKDIR: ${WORKDIR}
        CONTAINER_PORT: ${FRONT_CONTAINER_PORT}
        API_URL: http://localhost:${API_PORT}
    container_name: mwk-dev-frontend
    command: yarn dev
    depends_on:
      - backend
    ports:
      - "${FRONT_PORT}:${FRONT_CONTAINER_PORT}"
    volumes:
      - ./frontend:/${WORKDIR}:cached
      - node_modules_volume:/${WORKDIR}/node_modules

volumes:
  mkw-dev-db-data:
  mkw-dev-bundle_data:
  node_modules_volume:
